app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from app import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('user_app.urls')),
    path('', include('core.urls')),
    path('api/', include('api_app.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('settings/', include('settings_app.urls')),
    path('community/', include('community_app.urls')),
    path('messaging/', include('messaging_app.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/core/urls.py
""" Routes for the core_app """

from django.urls import path
from .views.main import (debug, index, landing_page, legal_disclosure,
                         privacy, cookie_disclosure, question_and_answers)
from .views import search

# Configuration
app_name = 'core'

# Routes
urlpatterns = [
    # Debug
    path('debug', debug, name='debug'),

    # Index
    path('', index, name='index'),

    # Landing Page
    path('landing',  landing_page, name='landing'),

    # Legal Disclosure
    path('impressum', legal_disclosure, name='legal_disclosure'),

    # Privacy
    path('datenschutz', privacy, name='privacy'),

    # Cookie Disclosure
    path('cookies', cookie_disclosure, name='cookie_disclosure'),

    # Cookie Disclosure
    path('question-and-answers', question_and_answers, name='qaa'),

    # Search results
    path('search/', search.results, name='search_results')

]

app/dashboard_app/urls.py
from django.urls import path
from dashboard_app.views import main, transaction, watchlist


app_name = 'dashboard_app'

urlpatterns = [
    # Overview
    path('<int:timespan>', main.dashboard, name="dashboard"),

    # Asset
    path('asset/<str:name>/<int:timespan>', main.asset, name="asset"),

    # Coin Overview
    path('coin_overview/<str:sort_by_attribute>/<str:direction>', main.coin_overview, name="coin_overview"),

    # Watchlist
    path('watchlist/list/<str:username>/<str:sort_by_attribute>/<str:direction>',
         main.watchlist, name="watchlist"),
    path('watchlist/add/<str:asset_symbol>',
         watchlist.watchlist_add, name="watchlist_add"),
    path('watchlist/price_change/<str:asset_symbol>/<int:price_change_time>',
         watchlist.watchlist_update_asset_price_change, name="watchlist_update_asset_price_change"),

    # Transaction
    path("transaction/list", main.transactions, name="transactions"),
    path("transaction/add/<str:coin>", transaction.add, name="transaction_add"),
    path("transaction/delete/<int:transaction_id>",
         transaction.delete, name="transaction_delete"),
    path("transaction/update/<int:transaction_id>",
         transaction.update, name="transaction_update"),
]

app/settings_app/urls.py
""" 
This module defines the URL patterns for the settings_app app.
"""

from django.urls import path, include
from . import views

app_name = 'settings_app'

urlpatterns = [
    path('userSettings/', views.user_settings, name='userSettings'),
    path('securitySettings/', views.security_settings, name='securitySettings'),
    path('securitySettings/update', views.security_settings_update,
         name='security_settings_update'),
    path('portfolioSettings/', views.portfolio_settings, name='portfolioSettings'),
    path('viewSettings/', views.view_settings, name='viewSettings'),
    path('notificationSettings/', views.notification_settings,
         name='notificationSettings'),
]

app/user_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PasswordCustomResetForm, PasswordCustomSetForm
from .views import profile, auth, profile_edit

app_name = 'user_app'

urlpatterns = [
    # Loading and redirecting to profile page 
    path('profile-redirect/', profile.profile_redirect, name='profile_redirect'),
    path('profile/<str:username>/<int:timespan>/',
         profile.profile, name='profile'),

    # Following 
    path('follow/<str:username>', profile.toggle_follow, name='follow'),

    # Update Routes       
    path('update/userprofile/<int:pk>',
          profile_edit.ProfilePicUpdateView.as_view(), name='update_userprofile'),   
    path('update/userbanner/<int:pk>',
          profile_edit.ProfileBannerUpdateView.as_view(), name='update_userbanner'),
    path("update/biography", 
         profile_edit.BiographyUpdateView.as_view(), name="update_biography"),
    path('delete/userprofile/<int:pk>',
         profile_edit.delete_profile_pic, name='delete_userprofile'),

    # Registration
    path('register', auth.register, name='register'),
    path('register/success', auth.register_success, name='register_success'),

    # Auth
    path('login', auth_views.LoginView.as_view(
        template_name='user_app/login.html', authentication_form=UserLoginForm), name='login'),
    path('logout', auth_views.LogoutView.as_view(
        template_name='core/landing.html'), name='logout'),

    # Password reset
    path('password-reset/',
         auth.ResetPasswordView.as_view(
             template_name="user_app/password_recovery/reset_password.html",
             form_class=PasswordCustomResetForm),
         name='reset_password'),
    path('password-reset-sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="user_app/password_recovery/reset_password_sent.html"),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth.ConfirmResetPasswordView.as_view(
             template_name="user_app/password_recovery/reset_password_confirm.html",
             form_class=PasswordCustomSetForm),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="user_app/password_recovery/reset_password_complete.html"),
         name='password_reset_complete'),
]

app/core/models.py
""" Models for the core_app """

# Create your models here.
from django.db import models
from user_app.models import CustomUser


class Asset(models.Model):
    assetname = models.CharField(max_length=50)


class Receipt(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE)
    amount = models.FloatField()
    buydate = models.DateTimeField("date bought")


class History(models.Model):
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE)
    value = models.FloatField()
    date = models.DateTimeField("value at date")

app/core/views.py
""" Views for the core_app """

from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from api_app.models import Asset
from user_app.models import CustomUser
from django.db.models import Q
from user_app import views as user_views


def debug(request):
    """ Render a custom url for debug purposes. """

    url = 'core/base.html'
    return render(request, url)


def index(request):
    """ 
        Render either the landing page or a user's profile page 
        depending on a user's authentication status. 
    """

    if request.user.is_authenticated:
        return user_views.profile(request, request.user.username, 0)

    return render(request, 'core/landing.html')


def landing_page(request):
    """ Render the landing page. """

    return render(request, 'core/landing.html')


def register(request):
    """ Render the registration page. """
    return render(request, '')


def signin(request):
    """ Render the login page. """

    return render(request, '')


def legal_disclosure(request):
    """ Render the legal disclosure page. """

    return render(request, 'core/legal_disclosure.html')


def privacy(request):
    """ Render the privacy disclosure page. """

    return render(request, 'core/privacy.html')


def cookie_disclosure(request):
    """ Render the cookie disclosure page. """

    return render(request, 'core/cookie_disclosure.html')


def question_and_answers(request):
    """ Render the questions and answers page. """

    return render(request, 'core/questions_and_answers.html')


def search_results(request):
    # Get the search value from the request
    search_value = request.GET.get('username', '')

    # Search for users and assets with a similar search value 
    user_results = CustomUser.objects.filter(username__icontains=search_value)
    asset_results = Asset.objects.filter(Q(name__icontains=search_value) | Q(coinName__icontains=search_value))

    # Get the following-list by the signed user 
    user_following_list = request.user.following.values_list(
        "following_user_id", flat=True)
    
    # Create the result dictionary with the corresponding lists and hand them over to the template 'search_result.html'
    results = {'users': user_results, 'assets': asset_results, 'followers': user_following_list}
    response = [render_to_string('inclusion/search_result.html', results)]

    return JsonResponse({'results': response})

app/core/views/search.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from api_app.models import Asset
from user_app.models import CustomUser
from django.db.models import Q


def results(request):
    # Get the search value from the request
    search_value = request.GET.get('input', '')

    # Search for users and assets with a similar search value
    user_results = CustomUser.objects.filter(Q(username__icontains=search_value) | Q(
        first_name__icontains=search_value) | Q(last_name__icontains=search_value))[:5]
    asset_results = Asset.objects.filter(
        Q(name__icontains=search_value) | Q(coinName__icontains=search_value))[:5]

    # Get the following-list by the signed user
    user_following_list = request.user.following.values_list(
        "following_user_id", flat=True)

    # Create the result dictionary with the corresponding lists and hand them over to the template 'search_result.html'
    results = {'users': user_results, 'assets': asset_results,
               'followers': user_following_list}
    response = [render_to_string('inclusion/search_result.html', results)]

    return JsonResponse({'results': response})

app/core/templates/inclusion/footer.html
{% load i18n %}
<div class="row">
    <div class="col p-2 border-top"> 

        {# Copyright #}
        <div class="small pb-2 text-center">
            <div>
                Copyright © 2023 
            </div>
            <div>
                Dimitri Dorn, Julian Müller, Nico Isheim, Maximilian Steinberg, Michael Sievers
            </div>
        </div>
       
        {# Links #}
        <div class="d-flex">
            <div class="d-flex gap-2 m-auto px-4 pt-2 border-top border-2">
                <div><a href="{% url 'core:legal_disclosure' %}">{% trans "Impressum" %}</a></div>
                <div>|</div>
                <div><a href="{% url 'core:privacy' %}">{% trans "Datenschutz" %}</a></div>
                <div>|</div>
                <div><a href="{% url 'core:cookie_disclosure' %}">{% trans "Cookie-Erklärung" %}</a></div>
            </div>
        </div>
        
    </div>
</div>

app/core/templates/inclusion/logo.html
{% load static %}

<div class="h-100">

</div>

{% comment %} <a href="">
    <img src="{% static 'img/logo.png' %}" alt="logo"">
</a> {% endcomment %}

app/core/templates/inclusion/logo_name.html
{% load static %}

<div class="col-auto my-auto d-flex me-auto" >
    <a href="{% url 'core:index' %}" class="nav-link d-flex">
        <div class="logo">
            <img src="{% static 'img/logo.png' %}" alt="logo" class="h-100">  
        </div>
        <div class="fs-3 fw-bold my-auto ms-2 text-gradient">Sociofolio</div>
    </a>
</div>

app/core/templates/inclusion/navigation.html
{% load core_tags %}
{% load i18n %}
<ul class="nav nav-pills flex-column mb-auto">
    <div class="fw-semibold user-select-none">{% trans "Portfolio" %}</div>
    {% trans "Dashboard" as dashboard %}
    {% trans "Watchlist" as watchlist %}
    {% trans "Coin Overview" as coin_overview %}
    {% trans "Transaktionen" as transactions %}
    {% navigation_button dashboard "bi-pie-chart-fill" "dashboard_app:dashboard" "0" %}
    {% navigation_button watchlist "bi-star-fill" "dashboard_app:watchlist" username "no_sort" 'n' %}
    {% navigation_button transactions "bi-file-diff-fill" "dashboard_app:transactions" %}
    {% navigation_button coin_overview "bi-coin" "dashboard_app:coin_overview" "no_sort" 'n' %}
    <div class="fw-semibold mt-4 user-select-none">{% trans "Sozial" %}</div>
    {% trans "Profil" as profil %}
    {% trans "Community" as community %}
    {% trans "Nachrichten" as messages %}
    {% navigation_button profil "bi-person-fill" "user_app:profile" username 0 %}
    {% navigation_button community "bi-share-fill" "community_app:community" "all" %}
    {% navigation_button messages "bi-chat-text-fill" "messaging_app:inbox" %}
</ul>

app/core/templates/inclusion/navigation_button.html
<li class="nav-item pt-2">
    <a class="btn btn-nav w-100 fs-5" href="{{ route }}">
        <div class="d-flex">
            <i class="bi {{ icon }} my-auto"></i>
            <div class="ps-2">{{ name }}</div>
        </div>
    </a>
</li>

app/core/templates/inclusion/search.html
{% load core_tags %}
{% load i18n %}
{% trans "Suche" as search_placeholder %}
<form id="search-form"
      method="get"
      action="{% url 'core:search_results' %}"
      class="my-auto">
    <div class="input-group my-auto mx-auto" style="max-width: {{ width }}%">
        <div class="position-absolute pt-4 px-2 pb-2 mt-3 w-100 bg-dark rounded border"
             id="search_results"
             style="display: none">
            <table class="table align-middle mb-0">
                <tbody id="search-results-list">
                    <!-- Search results will be dynamically populated here -->
                </tbody>
            </table>
        </div>
        <div class="input-group m-0">
            <span class="input-group-text"><i class="bi bi-search"></i></span>
            <input type="text"
                   name="input"
                   id="search_input"
                   autocomplete="off"
                   class="form-control"
                   placeholder="{{ search_placeholder }}"
                   aria-label="Suche"
                   oninput="search()">
        </div>
    </div>
</form>
{% comment %} <form id="search-form" method="get" action="{% url 'core:search_results' %}" class="inline my-auto mx-auto" style="max-width: {{ width }}%">
    <div class="input-group">
        <span class="input-group-text" id="basic-addon1"><i class="bi bi-search"></i></span>
        <input type="text" name="username" class="form-control" placeholder="Suche" aria-label="Suche">
        <button type="submit" class="btn btn-outline-primary">{% trans "Suche" %}</button>
    </div>
</form>
{% search_modal %} {% endcomment %}
<script>
    const search_results = document.getElementById("search_results");

    function search(){
        
        var input = $('input[name="input"]').val();
        if(input.length > 0) {

            // Fetch results
            $.ajax({
                url: {% url 'core:search_results' %},
                type: 'GET',
                data: { input: input },
                success: function(response) {
                    // Clear previous search results
                    $('#search-results-list').empty();
                    console.log(response);
                    
                    // Check if results exist 
                    if (response.results.length > 0) {
                        // Append search results to the modal
                        response.results.forEach(function(userResult) {
                            $('#search-results-list').append(userResult);
                        });
                    } else {
                        // Display a message when no results are found
                        $('#search-results-list').append('<li>No results found.</li>');
                    }
                }
            }); 
            search_results.style.display = "block";
        } else {
            search_results.style.display = "none";
        }
    }
</script>

app/core/templates/inclusion/search_modal.html
{% load i18n %}
<div class="modal fade"
     id="search-results-modal"
     tabindex="-1"
     aria-labelledby="search-results-modal-title"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="search-results-modal-title">{% trans "Suchergebnisse" %}</h1>
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table align-middle mb-0">
                        <tbody id="search-results-list">
                            <!-- Search results will be dynamically populated here -->
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button"
                        class="btn btn-outline-primary ms-auto"
                        data-bs-dismiss="modal">{% trans "Schließen" %}</button>
            </div>
        </div>
    </div>
</div>

app/core/templates/inclusion/search_result.html
{% load core_tags %}
{% load i18n %}
{% if not users and not assets %}
    <tr>
        <td class="border-0">
            <span>{% trans "Keine Ergebnisse gefunden!" %}</span>
        </td>
    </tr>
{% endif %}
{% if users %}
    <tr class="border-0">
        <td class="border-0 fs-5 fw-semibold text-white">{% trans "Nutzer" %}</td>
    </tr>
    {% for user in users %}
        <tr>
            <td colspan="100" class="border-0">
                <a class="btn btn-link text-start gap-2 w-100 d-flex bg-body-secondary p-2 border rounded"
                   href="{% url 'user_app:profile' user.username 0 %}">
                    <div class="my-auto">
                        <img class="logo-fs-3" src="{{ user.userprofileinfo.get_profile_pic }}">
                    </div>
                    <div>
                        <div>
                            <small>u/{{ user.username }}</small>
                        </div>
                        <div>{{ user.first_name }} {{ user.last_name }}</div>
                    </div>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endif %}
{% if assets %}
    <tr>
        <td class="border-0 fs-5 fw-semibold text-white">Assets</td>
    </tr>
    {% for asset in assets %}
        <tr>
            <td colspan="100" class="border-0">
                <a href="{% url 'dashboard_app:asset' asset.name 0 %}"
                   class="btn btn-link text-start gap-2 w-100 d-flex bg-body-secondary p-2 border rounded">
                    <div class="my-auto">
                        <img class="logo-fs-3" src="{{ asset.imageUrl }}">
                    </div>
                    <div>
                        <div>
                            <small>{{ asset.name }}</small>
                        </div>
                        <div>{{ asset.coinName }}</div>
                    </div>
                    <div class="ms-auto my-auto">{{ asset.price|to_locale_valuta }}</div>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endif %}

app/core/templates/inclusion/user_menu.html
{% load i18n %}
<div class="col-auto">
    <div class="dropdown">
        <button class="btn btn-link h-100 pe-0 position-relative"
                type="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
                id="notificationButton">
            <i class="bi bi-bell-fill fs-5"></i>
        </button>
        <ul class="dropdown-menu" id="dropdownMenu">
            <button class="dropdown-item btn btn-danger h-100 d-flex justify-content-center"
                    id="deleteButton">
                <i class="bi bi-trash"></i>
            </button>
        </ul>
    </div>
</div>
<div class="col-auto">
    <div class="dropdown">
        <button class="btn btn-link h-100 ps-0"
                type="button"
                data-bs-toggle="dropdown"
                aria-expanded="false">
            <img class="logo-fs-3"
                 src="{{ request.user.userprofileinfo.get_profile_pic }}">
        </button>
        <ul class="dropdown-menu">
            <li class="text-center">
                <p class="my-2 text-body-emphasis fw-bold">{{ request.user.first_name }} {{ request.user.last_name }}</p>
            </li>
            <li>
                <a class="dropdown-item"
                   href="{% url 'user_app:profile' request.user.username 0 %}"><i class="bi bi-person-fill pe-2"></i>{% trans "Profil" %}</a>
            </li>
            <li>
                <a class="dropdown-item" href="{% url 'core:qaa' %}"><i class="bi bi-info-circle pe-2"></i>{% trans "Hilfe" %}</a>
            </li>
            <li>
                <a class="dropdown-item" href="{% url 'settings_app:userSettings' %}"><i class="bi bi-gear pe-2"></i>{% trans "Einstellungen" %}</a>
            </li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li>
                <a class="dropdown-item text-danger-emphasis"
                   href="{% url 'user_app:logout' %}"><i class="bi bi-box-arrow-in-left pe-2"></i>{% trans "Abmelden" %}</a>
            </li>
        </ul>
    </div>
</div>
<script>
        const openDropdownButton = document.getElementById('notificationButton');
        const dropdown = document.getElementById('dropdownMenu');
        const deleteButton = document.getElementById('deleteButton')

        let websocket;
    
        var loc = window.location
        var wsStart = "ws://"
        if (loc.protocol == "https:"){
            wsStart = "wss://"
        }
        var webSocketEndpoint =  wsStart + loc.host + '/notifications/'  // ws : wss   // Websocket URL, Same on as mentioned in the routing.py
    
        websocket = new WebSocket(webSocketEndpoint);
        let messages = [];
        
        websocket.onmessage = function(e){
            messages = []
            const messageObject = JSON.parse(e.data)
            console.log(messageObject)
            if(messageObject.type === "websocket.all_notifications"){
            
                const notifications = messageObject.notifications
            
                for(let key in notifications){
                    messages.push(notifications[key].message)
                }
                
            }
        }

        openDropdownButton.addEventListener('click', () => {
            removeAllItems(dropdown)


            messages.forEach((notification) => {
                const listItem = document.createElement('li');
                listItem.classList.add('dropdown-item');
                listItem.classList.add('items');

                const text = document.createElement('p')
                const node = document.createTextNode(notification);
                text.appendChild(node)
                listItem.appendChild(text);

                const divider = document.createElement('hr')
                divider.classList.add('dropdown-divider')
                listItem.appendChild(divider)

                dropdown.insertBefore(listItem, dropdown.firstChild)
            })
        })

        deleteButton.addEventListener('click', () => {
            websocket.send("deleteAllNotifications")
        })

        function removeAllItems(parent) {
            const items = document.querySelectorAll('.items')
            items.forEach(item => item.remove());
        }
        
</script>