app/api_app/urls.py
from django.urls import path
from api_app.views import coin, main
app_name = 'api_app'

urlpatterns = [
    #Main
    path('api', main.api_admin_panel, name="api_admin_panel"),

    #Coin
    path('api/add/coin', coin.add_coin, name="add_coin"),
    path('api/add/asset_data', coin.add_asset_data, name="add_asset_data"),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from app import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('user_app.urls')),
    path('', include('core.urls')),
    path('api/', include('api_app.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('settings/', include('settings_app.urls')),
    path('community/', include('community_app.urls')),
    path('messaging/', include('messaging_app.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/settings_app/urls.py
""" 
This module defines the URL patterns for the settings_app app.
"""

from django.urls import path, include
from . import views

app_name = 'settings_app'

urlpatterns = [
    path('userSettings/', views.user_settings, name='userSettings'),
    path('securitySettings/', views.security_settings, name='securitySettings'),
    path('securitySettings/update', views.security_settings_update,
         name='security_settings_update'),
    path('portfolioSettings/', views.portfolio_settings, name='portfolioSettings'),
    path('viewSettings/', views.view_settings, name='viewSettings'),
    path('notificationSettings/', views.notification_settings,
         name='notificationSettings'),
]

app/settings_app/models.py
""" 
This file contains the models for the settings_app. 
"""

from django.db import models

from user_app.models import CustomUser


# Create your models here.


class Settings(models.Model):
    """
    This class represents the settings model.
    """

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

    # Portfoliosettings field's
    dateTimeFormat = models.CharField(
        max_length=30, blank=False, default="DD.MM.YYYY HH:mm")
    currency = models.CharField(max_length=30, blank=False, default="EUR")

    # Notificationsettings field's
    hasAssetAmountChanged = models.BooleanField(default=True)
    hasNewFollower = models.BooleanField(default=True)
    hasLikedPost = models.BooleanField(default=True)
    hasLikedComment = models.BooleanField(default=True)
    hasNewComment = models.BooleanField(default=True)
    hasSharedPost = models.BooleanField(default=True)

    #Post Settings
    posts_privacy_settings = models.CharField(max_length=10, default="all")

    # Watchlist Settings
    watchlist_privacy_settings = models.CharField(max_length=10, default="all")

    # Dashboard Settings
    dashboard_privacy_settings = models.CharField(max_length=10, default="all")

    # Displaysettings field's
    theme = models.CharField(max_length=30, blank=False, default="dark")

    # View Setting Language
    language = models.CharField(max_length=30, blank=False, default="de")
    
    def __str__(self):
        return self.user.username + "'s settings"

app/settings_app/forms.py
""" 
This file contains all forms for the settings_app. 
"""

from django import forms

from user_app.models import CustomUser
from .models import Settings
from django.utils.translation import gettext_lazy as _
# TODO: Template String für Internationalisierung der Dropdown Texte
CHOICES = [(False, 'Deaktiviert'), (True, 'Aktiviert')]


class UserSettingsForm(forms.ModelForm):
    """
    This class represents the user settings form.
    """
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        "id": "first_name",
        "class": "form-control",
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        "id": "last_name",
        "class": "form-control",
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        "id": "username",
        "class": "form-control",
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        "id": "email",
        "class": "form-control",
    }))

    class Meta:
        model = CustomUser
        fields = ["username", "email", "first_name", "last_name"]
        labels = {
            "username": _("Benutzername"),
            "email": _("Email"),
            "first_name": _("Vorname"),
            "last_name": _("Name")
        }


class PortfolioSettingsForm(forms.ModelForm):
    """
    This class represents the portfolio settings form.
    """
    date_format_choices = (
        ("DD.MM.YYYY HH:mm", "DD.MM.YYYY HH:mm"),
        ("MM/DD/YYYY HH:mm", "MM/DD/YYYY HH:mm"),
        ("YYYY-MM-DD HH:mm", "YYYY-MM-DD HH:mm")
    )

    dateTimeFormat = forms.ChoiceField(widget=forms.Select(
        attrs={
            "id": "dateTimeFormat",
            "class": "form-control"
        }),
        choices=date_format_choices)

    class Meta:
        model = Settings
        fields = ["dateTimeFormat", "currency", "theme"]


class NotificationSettingsForm(forms.ModelForm):
    hasAssetAmountChanged = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        "id": "hasAssetAmountChanged",
        "role": "switch",
        "class": "form-check-input"
    }))
    hasNewFollower = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        "id": "hasNewFollower",
        "role": "switch",
        "class": "form-check-input"
    }))
    hasLikedPost = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        "id": "hasLikedPost",
        "role": "switch",
        "class": "form-check-input"
    }))
    hasLikedComment = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        "id": "hasLikedComment",
        "role": "switch",
        "class": "form-check-input"
    }))
    hasNewComment = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        "id": "hasNewComment",
        "role": "switch",
        "class": "form-check-input"
    }))
    hasSharedPost = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        "id": "hasSharedPost",
        "role": "switch",
        "class": "form-check-input"
    }))

    """
    This class represents the notification settings form.
    """
    class Meta:
        model = Settings
        fields = ["hasAssetAmountChanged", "hasNewFollower", "hasLikedPost",
                  "hasLikedComment", "hasNewComment", "hasSharedPost"]


class SecuritySettingsForm(forms.Form):
    posts_privacy_setting = forms.CharField(label="Posts Privacy Setting", widget=forms.Select(
        choices=[("all", "all"), ("private", "private")],
        attrs={"class": "form-control",
               "id": "posts_privacy_setting"}),
        required=True)
    watchlist_privacy_setting = forms.CharField(label="Watchlist Privacy Setting", widget=forms.Select(
        choices=[("all", "all"), ("private", "private")],
        attrs={"class": "form-control",
               "id": "watchlist_privacy_setting"}),
        required=True)
    dashboard_privacy_setting = forms.CharField(label="Dashboard Privacy Setting", widget=forms.Select(
        choices=[(
            "all", "all"), ("without values", "without values"), ("private", "private")],
        attrs={"class": "form-control",
               "id": "dashboard_privacy_setting"}),
        required=True)


class LanguageSettingsForm(forms.Form):
    language = forms.CharField(label="Language", widget=forms.Select(
        choices=[("de", "Deutsch (de)"), ("en-us", "Englisch (en)")],
        attrs={"class": "form-control",
               "id": "language_setting"}),
        required=True)

app/settings_app/views.py
"""
This file contains all views for the settings app.
"""

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from user_app.models import CustomUser
from .models import Settings
from .forms import NotificationSettingsForm, UserSettingsForm, SecuritySettingsForm, LanguageSettingsForm
from django.http import HttpResponseRedirect
from django.utils import translation
from community_app.models import Post
from dashboard_app.models import Watchlist
from app.settings import LANGUAGE_CODE


@login_required
def settings(request):
    """
    Renders the settings overview page.
    """
    return render(request, 'settings_app/settingsOverview.html', {"user": request.user})


@login_required
def user_settings(request):
    """
    Renders the user settings page.
    """
    user = CustomUser.objects.get(id=request.user.id)
    form = UserSettingsForm(instance=user)

    if request.method == "POST":
        form = UserSettingsForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
    return render(request, 'settings_app/userSettings.html', {'form': form})


@login_required
def security_settings(request):
    """
    Renders the security settings page.
    """
    settings = Settings.objects.get(user=request.user)
    form = SecuritySettingsForm(initial={"posts_privacy_setting": settings.posts_privacy_settings,
                                "watchlist_privacy_setting": settings.watchlist_privacy_settings, "dashboard_privacy_setting": settings.dashboard_privacy_settings})
    data = {"form": form}
    return render(request, 'settings_app/securitySettings.html', context=data)


@login_required
def security_settings_update(request):
    settings = Settings.objects.get_or_create(user=request.user)[0]
    form = SecuritySettingsForm(request.POST)
    if form.is_valid():
        form_data = form.cleaned_data
        Settings.objects.filter(id=settings.id).update(posts_privacy_settings=form_data["posts_privacy_setting"], watchlist_privacy_settings=form_data[
            "watchlist_privacy_setting"], dashboard_privacy_settings=form_data["dashboard_privacy_setting"])
        Watchlist.objects.filter(user=request.user).update(
            privacy_settings=form_data["watchlist_privacy_setting"])
        Post.objects.filter(user=request.user).update(
            privacy_settings=form_data["posts_privacy_setting"])
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def portfolio_settings(request):
    """
    Renders the portfolio settings page.
    """

    if request.method == "POST":
        Settings.objects.filter(user=request.user).update(
            dateTimeFormat=request.POST["dateTimeFormat"],
            currency=request.POST["currencySelector"]
        )

    return render(request, 'settings_app/portfolioSettings.html')


@login_required
def notification_settings(request):
    """
    Renders the notification settings page.
    """
    setting = Settings.objects.get_or_create(user=request.user)[0]
    form = NotificationSettingsForm(
        initial={
            'hasAssetAmountChanged': setting.hasAssetAmountChanged,
            'hasNewFollower': setting.hasNewFollower,
            'hasLikedPost': setting.hasLikedPost,
            'hasLikedComment': setting.hasLikedComment,
            'hasNewComment': setting.hasNewComment,
            'hasSharedPost': setting.hasSharedPost
        })

    if request.method == "POST":
        form = NotificationSettingsForm(request.POST)
        if form.is_valid():
            setting.hasAssetAmountChanged = form.cleaned_data["hasAssetAmountChanged"]
            setting.hasNewFollower = form.cleaned_data["hasNewFollower"]
            setting.hasLikedPost = form.cleaned_data["hasLikedPost"]
            setting.hasLikedComment = form.cleaned_data["hasLikedComment"]
            setting.hasNewComment = form.cleaned_data["hasNewComment"]
            setting.hasSharedPost = form.cleaned_data["hasSharedPost"]

            setting.save()

    return render(request, 'settings_app/notificationSettings.html', {'form': form})


@login_required
def view_settings(request):
    """
    Renders the view settings page.
    """
    form = LanguageSettingsForm(initial={"language": translation.get_language})
    data = {"form": form}
    if request.method == "POST":
        return HttpResponseRedirect("")
    return render(request, 'settings_app/viewSettings.html',context=data)

app/settings_app/templates/settings_app/notificationSettings.html
{% extends "settings_app/settingsOverview.html" %}
{% load i18n %}
{% block settings_title %}
    {% trans "Benachrichtigungseinstellungen" %}
{% endblock settings_title %}
{% block class_selector_notification %}
    chat-user-entry-selected
{% endblock class_selector_notification %}
{% block settings %}
    <div class="form-check form-switch">
        <label for="{{ form.hasAssetAmountChanged.id_for_label }}"
               class="form-label ms-2">{% trans "Veränderung der Assetmenge" %}</label>
        {{ form.hasAssetAmountChanged }}
    </div>
    <div class="form-check form-switch">
        <label for="{{ form.hasNewFollower.id_for_label }}" class="form-label ms-2">{% trans "Neuer Follower" %}</label>
        {{ form.hasNewFollower }}
    </div>
    <div class="form-check form-switch">
        <label for="{{ form.hasLikedPost.id_for_label }}" class="form-label ms-2">{% trans "Beitrags Like" %}</label>
        {{ form.hasLikedPost }}
    </div>
    <div class="form-check form-switch">
        <label for="{{ form.hasLikedComment.id_for_label }}" class="form-label ms-2">{% trans "Kommentar Like" %}</label>
        {{ form.hasLikedComment }}
    </div>
    <div class="form-check form-switch">
        <label for="{{ form.hasNewComment.id_for_label }}" class="form-label ms-2">{% trans "Neuer Kommentar" %}</label>
        {{ form.hasNewComment }}
    </div>
    <div class="form-check form-switch">
        <label for="{{ form.hasSharedPost.id_for_label }}" class="form-label ms-2">{% trans "Beitrag geteilt" %}</label>
        {{ form.hasSharedPost }}
    </div>
{% endblock settings %}

app/settings_app/templates/settings_app/portfolioSettings.html
{% extends "settings_app/settingsOverview.html" %}
{% load i18n %}
{% block settings_title %}
    {% trans "Portfolioeinstellungen" %}
{% endblock settings_title %}
{% block class_selector_portfolio %}
    chat-user-entry-selected
{% endblock class_selector_portfolio %}
{% block settings %}
    <div>
        <label for="dateTimeFormat" class="form-label">{% trans "Datums- und Zeitformat" %}</label>
        <select name="dateTimeFormat" class="form-control" id="dateTimeFormat">
            <option>DD.MM.YYYY HH:mm</option>
            <option>MM/DD/YYYY HH:mm</option>
            <option>YYYY-MM-DD HH:mm</option>
        </select>
    </div>
    <div>
        <label for="currencySelector" class="form-label">{% trans "Währung" %}</label>
        <select name="currencySelector" class="form-control" id="currencySelector">
            <option>{% trans "Euro" %}</option>
            <option>{% trans "USD" %}</option>
            <option>{% trans "Pfund" %}</option>
            <option>{% trans "Rubel" %}</option>
        </select>
    </div>
{% endblock settings %}

app/settings_app/templates/settings_app/securitySettings.html
{% extends "settings_app/settingsOverview.html" %}
{% load i18n %}
{% block settings_title %}
    {% trans "Sicherheitseinstellungen" %}
{% endblock settings_title %}
{% block class_selector_security %}
    chat-user-entry-selected
{% endblock class_selector_security %}
{% block url %}
    {% url "settings_app:security_settings_update" %}
{% endblock url %}
{% block settings %}
    <div>
        <label for="{{ form.posts_privacy_setting.id_for_label }}"
               class="form-label">Posts</label>
        {{ form.posts_privacy_setting }}
    </div>
    <div>
        <label for="{{ form.watchlist_privacy_setting.id_for_label }}"
               class="form-label">Watchlist</label>
        {{ form.watchlist_privacy_setting }}
    </div>
    <div>
        <label for="{{ form.dashboard_privacy_setting.id_for_label }}"
               class="form-label">Dashboard</label>
        {{ form.dashboard_privacy_setting }}
    </div>
{% endblock settings %}

app/settings_app/templates/settings_app/settingsOverview.html
{% extends "core/base.html" %}
{% load i18n %}
{% block title %}
    | Einstellungen
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-12">
            <h1>{% trans "Einstellungen" %}</h1>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-auto gap-2 d-flex flex-column">
            <a class="d-flex gap-2 p-2 rounded border {% block class_selector_user %}chat-user-entry{% endblock class_selector_user %}"
               href="{% url 'settings_app:userSettings' %}">{% trans "Profileinstellungen" %}</a>
            <a class="d-flex gap-2 p-2 rounded border {% block class_selector_portfolio %}chat-user-entry{% endblock class_selector_portfolio %}"
               href="{% url 'settings_app:portfolioSettings' %}">{% trans "Portfolioeinstellungen" %}</a>
            <a class="d-flex gap-2 p-2 rounded border {% block class_selector_security %}chat-user-entry{% endblock class_selector_security %}"
               href="{% url 'settings_app:securitySettings' %}">{% trans "Sicherheitseinstellungen" %}</a>
            <a class="d-flex gap-2 p-2 rounded border {% block class_selector_notification %}chat-user-entry{% endblock class_selector_notification %}"
               href="{% url 'settings_app:notificationSettings' %}">{% trans "Benachrichtigungseinstellungen" %}</a>
            <a class="d-flex gap-2 p-2 rounded border {% block class_selector_view %}chat-user-entry{% endblock class_selector_view %}"
               href="{% url 'settings_app:viewSettings' %}">{% trans "Anzeigeeinstellungen" %}</a>
            {% if user.is_superuser == 1 %}
                <a class="d-flex gap-2 p-2 rounded border {% block class_selector_admin %}chat-user-entry{% endblock class_selector_admin %}"
                   href="{% url 'api_app:api_admin_panel' %}">{% trans "API-Admin Panel" %}</a>
            {% endif %}
        </div>
        <div class="col">
            <div class="card">
                <div class="card-header d-flex">
                    <div class="fs-3">
                        {% block settings_title %}
                        {% endblock settings_title %}
                    </div>
                </div>
                <form class="m-0" method="post" action="{% block url %} {% endblock url %}">
                    {% csrf_token %}
                    <div class="card-body d-flex gap-3 flex-column">
                        {% block settings %}
                        {% endblock settings %}
                    </div>
                    <div class="card-footer d-flex">
                        <button class="btn btn-outline-success ms-auto" type="submit">{% trans "Speichern" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

app/settings_app/templates/settings_app/userSettings.html
{% extends "settings_app/settingsOverview.html" %}
{% load i18n %}
{% block settings_title %}
    {% trans "Profileinstellungen" %}
{% endblock settings_title %}
{% block class_selector_user %}
    chat-user-entry-selected
{% endblock class_selector_user %}
{% block settings %}
    <div class="d-flex gap-3">
        <div class="w-100">
            <label for="{{ form.first_name.id_for_label }}" class="form-label">{% trans "Vorname" %}</label>
            {{ form.first_name }}
        </div>
        <div class="w-100">
            <label for="{{ form.last_name.id_for_label }}" class="form-label">{% trans "Nachname" %}</label>
            {{ form.last_name }}
        </div>
    </div>
    <div>
        <label for="{{ form.email.id_for_label }}" class="form-label">{% trans "E-Mail" %}</label>
        {{ form.email }}
    </div>
    <div>
        <label for="{{ form.username.id_for_label }}" class="form-label">{% trans "Benutzername" %}</label>
        {{ form.username }}
    </div>
{% endblock settings %}

app/settings_app/templates/settings_app/viewSettings.html
{% extends "settings_app/settingsOverview.html" %}
{% load i18n %}
{% block settings_title %}
    {% trans "Anzeigeeinstellungen" %}
{% endblock settings_title %}
{% block class_selector_view %}
    chat-user-entry-selected
{% endblock class_selector_view %}
{% block url %}
    {% url "set_language" %}
{% endblock url %}
{% block settings %}
    <div>
        <label for="{{ form.language.id_for_label }}" class="form-label">{% trans "Sprache" %}</label>
        {{ form.language }}
    </div>
{% endblock settings %}