app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from app import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('user_app.urls')),
    path('', include('core.urls')),
    path('api/', include('api_app.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('settings/', include('settings_app.urls')),
    path('community/', include('community_app.urls')),
    path('messaging/', include('messaging_app.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/dashboard_app/urls.py
from django.urls import path
from dashboard_app.views import main, transaction, watchlist


app_name = 'dashboard_app'

urlpatterns = [
    # Overview
    path('<int:timespan>', main.dashboard, name="dashboard"),

    # Asset
    path('asset/<str:name>/<int:timespan>', main.asset, name="asset"),

    # Coin Overview
    path('coin_overview/<str:sort_by_attribute>/<str:direction>', main.coin_overview, name="coin_overview"),

    # Watchlist
    path('watchlist/list/<str:username>/<str:sort_by_attribute>/<str:direction>',
         main.watchlist, name="watchlist"),
    path('watchlist/add/<str:asset_symbol>',
         watchlist.watchlist_add, name="watchlist_add"),
    path('watchlist/price_change/<str:asset_symbol>/<int:price_change_time>',
         watchlist.watchlist_update_asset_price_change, name="watchlist_update_asset_price_change"),

    # Transaction
    path("transaction/list", main.transactions, name="transactions"),
    path("transaction/add/<str:coin>", transaction.add, name="transaction_add"),
    path("transaction/delete/<int:transaction_id>",
         transaction.delete, name="transaction_delete"),
    path("transaction/update/<int:transaction_id>",
         transaction.update, name="transaction_update"),
]

app/messaging_app/urls.py
from django.urls import path
from messaging_app.views import inbox_chat, inbox, messages
app_name = 'messaging_app'

urlpatterns = [
    # Main
    path('inbox', inbox.inbox, name="inbox"),

    # Chat
    path('inbox/<str:participant_req>', inbox_chat.inbox_chat, name="inbox_chat"),
    path('inbox/add_message/<str:chat_participant_name>', messages.create_message, name="create_message"),
]

app/user_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PasswordCustomResetForm, PasswordCustomSetForm
from .views import profile, auth, profile_edit

app_name = 'user_app'

urlpatterns = [
    # Loading and redirecting to profile page 
    path('profile-redirect/', profile.profile_redirect, name='profile_redirect'),
    path('profile/<str:username>/<int:timespan>/',
         profile.profile, name='profile'),

    # Following 
    path('follow/<str:username>', profile.toggle_follow, name='follow'),

    # Update Routes       
    path('update/userprofile/<int:pk>',
          profile_edit.ProfilePicUpdateView.as_view(), name='update_userprofile'),   
    path('update/userbanner/<int:pk>',
          profile_edit.ProfileBannerUpdateView.as_view(), name='update_userbanner'),
    path("update/biography", 
         profile_edit.BiographyUpdateView.as_view(), name="update_biography"),
    path('delete/userprofile/<int:pk>',
         profile_edit.delete_profile_pic, name='delete_userprofile'),

    # Registration
    path('register', auth.register, name='register'),
    path('register/success', auth.register_success, name='register_success'),

    # Auth
    path('login', auth_views.LoginView.as_view(
        template_name='user_app/login.html', authentication_form=UserLoginForm), name='login'),
    path('logout', auth_views.LogoutView.as_view(
        template_name='core/landing.html'), name='logout'),

    # Password reset
    path('password-reset/',
         auth.ResetPasswordView.as_view(
             template_name="user_app/password_recovery/reset_password.html",
             form_class=PasswordCustomResetForm),
         name='reset_password'),
    path('password-reset-sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="user_app/password_recovery/reset_password_sent.html"),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth.ConfirmResetPasswordView.as_view(
             template_name="user_app/password_recovery/reset_password_confirm.html",
             form_class=PasswordCustomSetForm),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="user_app/password_recovery/reset_password_complete.html"),
         name='password_reset_complete'),
]

app/user_app/views.py
import os
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from user_app.models import CustomUser, UserProfileInfo, UserFollowing, ProfileBanner
from settings_app.models import Settings
from user_app.forms import UserRegistrationForm, UserProfileInfoForm, UserLoginForm
from dashboard_app.views import charts
from api_app.models import Asset
from dashboard_app.models import Transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from PIL import Image
from django.conf import settings
from django.db.models import Sum, F
from dashboard_app.views import kpi
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from community_app.views import post


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = "user_app/password_recovery/reset_password_email.html",
    subject_template_name = "user_app/password_recovery/reset_password_email_subject",
    success_url = reverse_lazy('user_app:password_reset_done')


class ConfirmResetPasswordView(PasswordResetConfirmView):
    success_url = reverse_lazy('user_app:password_reset_complete')

# Create your views here.


def register(request):
    registred = False

    if request.method == "POST":
        # Get the form data of the POST-method
        user_form = UserRegistrationForm(data=request.POST)
        userprofile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and userprofile_form.is_valid():

            # Save the user registration data from POST-form to the database and hash the password
            new_user = user_form.save()
            new_user.set_password(new_user.password)
            new_user.save()

            # Save the user-info registration data from POST-form to the database and connect them
            # to the previous user table
            new_profile = userprofile_form.save(commit=False)
            new_profile.user = new_user
            Settings.objects.get_or_create(user=new_user)

            if 'profile_pic' in request.FILES:
                new_profile.profile_pic = request.FILES['profile_pic']
            new_profile.save()

            # Create new ProfileBanner instance 
            ProfileBanner.objects.create(user=new_user)

            registred = True
            return render(request, 'user_app/register/registration_success.html')

        print(user_form.errors, userprofile_form.errors)

    else:
        user_form = UserRegistrationForm()
        userprofile_form = UserProfileInfoForm()

    return render(request, 'user_app/register/registration.html',
                  {'user_form': user_form,
                   'profile_form': userprofile_form,
                   'registred': registred})


def register_success(request):
    return render(request, 'user_app/register/registration_succsess.html')


@login_required
def profile_redirect(request):
    username = request.user.username
    profile_url = reverse('user_app:profile', kwargs={'username': username, 'timespan': 0})
    return redirect(profile_url)


@login_required
def profile(request, username, timespan):
    """ 
    Render a user-profile.

    Keyword arguments:
        request: The http request
        username: The profile user's username
    """

    # Get profile user
    profile_user = get_object_or_404(
        CustomUser.objects.select_related("userprofileinfo"), username=username)

    # Declare common variables
    user_following_list = request.user.following.values_list(
        "following_user_id", flat=True)
    is_user_profile = request.user.username == profile_user.username
    is_user_following = profile_user.userprofileinfo.id in user_following_list

    portfolio_privacy_setting = Settings.objects.get_or_create(user=profile_user)[0].dashboard_privacy_settings


    # Get profile user's follow-lists
    profile_followers_list = CustomUser.objects.filter(
        following__following_user_id=profile_user.id).select_related("userprofileinfo")
    profile_following_list = CustomUser.objects.filter(
        followers__follower_user_id=profile_user.id).select_related("userprofileinfo")

    # Post-Section
    my_posts = post.get_by_user(profile_user)
    postform = post.PostForm()

    # Chart Data

    transactions = Transaction.objects.filter(user=profile_user.id)
    assets = Asset.objects.filter(transaction__user=profile_user.id).annotate(
        amount=Sum("transaction__amount"),
        cost=Sum("transaction__cost"),
        total_value=F("amount") * F("price"),
        profit=F("total_value") - F("cost")
    ).distinct()

    if not assets:
        data = {"assets": None}

    has_transactions = False
    kpi_total = 0
    
    if transactions:
        kpi_total = kpi.get_kpi(transactions, assets)["total"]
        has_transactions = True

    if portfolio_privacy_setting == "without values":
        kpi_total = 0
        anonymize = True
    else:
        anonymize = False

    return render(request, 'user_app/profile.html',
                  {"profile_user": profile_user,
                   'user_profile_id': profile_user.userprofileinfo.id,
                   "is_user_profile": is_user_profile,
                   "is_user_following": is_user_following,
                   "portfolio_privacy_setting": portfolio_privacy_setting,
                   "profile_followers_list": profile_followers_list,
                   "profile_following_list": profile_following_list,
                   "user_following_list": user_following_list,
                   "postform": postform,
                   "myposts": my_posts,
                   "pie_data": charts.get_pie_data(assets, anonymize),
                    "line_data": charts.get_portfolio_line_data(transactions, timespan, anonymize),
                    "assets": assets,
                    "kpi_total": kpi_total,
                    "has_transactions":has_transactions,
                   })


@login_required
def toggle_follow(request, username):
    profile_user = CustomUser.objects.get(username=request.user.username)
    other_user = get_object_or_404(CustomUser, username=username)

    if profile_user != other_user:
        if profile_user.following.all().filter(following_user=other_user).exists():
            UserFollowing.objects.filter(
                follower_user=profile_user, following_user=other_user).delete()
        else:
            UserFollowing.objects.create(
                follower_user=profile_user, following_user=other_user)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def getUser(id):
    user = CustomUser.objects.get(id=id)
    return user


class ProfilePicUpdateView(LoginRequiredMixin, UpdateView):
    model = UserProfileInfo
    fields = ['profile_pic']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('user_app:profile_redirect')


class ProfileBannerUpdateView(LoginRequiredMixin, UpdateView):
    model = UserProfileInfo
    fields = ['profile_banner']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('user_app:profile_redirect')


@login_required
def update_user_profile_pic(request, pk):
    profile = UserProfileInfo.objects.get(id=pk)

    if request.method == 'POST':
        if 'profile_pic' in request.FILES:
            profile.profile_pic = request.FILES['profile_pic']
            profile.save()

    return redirect(reverse('user_app:profile_redirect'))


@login_required
def update_user_profile_banner(request, pk):
    profile = ProfileBanner.objects.get(id=pk)

    if request.method == 'POST':
        new_banner = request.POST.get('profile_banner')
        
        profile.profile_banner = getattr(ProfileBanner.BannerChoices, new_banner, None)
        profile.save()
        # if 'profile_banner' in request.FILES:
        #     profile.profile_banner = request.FILES['profile_banner']
        #     profile.profile_pic = profile.profile_pic
        #     profile.save()

    return redirect(reverse('user_app:profile_redirect'))


@login_required
def delete_profile_pic(request, pk):
    user_profile = get_object_or_404(UserProfileInfo, pk=pk)

    if pk == request.user.userprofileinfo.id:
        user_profile.profile_pic.delete()
        # user_profile.delete_profile_pic()

    return redirect(reverse('user_app:profile_redirect'))


@login_required
def follower_list(request, username):
    profile_user = CustomUser.objects.get(username=username)
    follower_list = []
    for follower in UserFollowing.objects.filter(following_user_id=profile_user.id):
        follower_user = CustomUser.objects.get(id=follower.follower_user_id)
        is_following = UserFollowing.objects.filter(
            following_user_id=follower.follower_user.id).filter(follower_user_id=request.user.id).exists()
        followerData = {"username": follower_user.username, "user_picture": profile_user.userprofileinfo.get_profile_pic(),
                        "is_following": is_following, "followers": follower_user.followers.count()}
        follower_list.append(followerData)
    data = {"follower": follower_list}
    return render(request, 'user_app/follower_list.html', context=data)

app/user_app/templates/user_app/login.html
{% extends "core/clear_base.html" %}
{% load i18n %}
{% load core_tags %}
{% block title %}
    | {% trans "Login" %}
{% endblock title %}
{% block content %}
    <div class="row h-100 m-auto">
        <div class="col-sm-10 col-md-8 col-lg-5 col-xl-5 col-xxl-4 m-auto">
            <div class="card">
                <div class="card-body">
                    <h1 class="text-center">{% trans "Anmeldung" %}</h1>
                    <form action="{% url 'user_app:login' %}" method="post">
                        {% csrf_token %}
                        <div class="mt-4">
                            <label for="username" class="form-label">{% trans "Benutzername" %}</label>
                            <div class="input-group">
                                <div class="input-group-text">
                                    <i class="bi bi-person-fill"></i>
                                </div>
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="mt-4">
                            <label for="password" class="form-label">{% trans "Passwort" %}</label>
                            <div class="input-group">
                                <div class="input-group-text">
                                    <i class="bi bi-key-fill"></i>
                                </div>
                                {{ form.password }}
                            </div>
                        </div>
                        {% if form.errors or form.non_field_errors %}
                            <div class="mt-4 text-danger-emphasis bg-danger-subtle d-flex rounded">
                                <div class="pe-2 bg-danger"
                                     style="border-start-start-radius: 0.375rem;
                                            border-end-start-radius: 0.375rem"></div>
                                <div class="px-3 pt-3">
                                    <strong>{% trans "Fehlgeschlagen" %}</strong>
                                    {% for field in form %}{{ field.errors }}{% endfor %}
                                    {{ form.non_field_errors }}
                                </div>
                            </div>
                        {% endif %}
                        {% trans "Anmelden" as sign_in_placeholder %}
                        <input class="btn btn-primary mt-4 w-100" type="submit" value="{{sign_in_placeholder}}">
                    </form>
                    <a href="{% url 'user_app:reset_password' %}">{% trans "Passwort vergessen?" %}</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

app/user_app/templates/user_app/profile.html
{% extends "core/base.html" %}
{% load user_tags %}
{% load community_tags %}
{% load dashboard_tags %}
{% load core_tags %}
{% load i18n %}
{% block title %}
    | {{ profile_user.first_name }} {{ profile_user.last_name }}
{% endblock title %}
{% block content %}
    <div class="card mb-3">
        <div class="position-relative">
            <img class="card-img-top"
                 style="max-height: 25vh"
                 src="{{ profile_user.profilebanner.get_profile_banner }}"
                 alt="Card image cap" />
            <div class="card-img-overlay d-flex flex-column justify-content-end align-items-center p-0">
                <div class="h-75 mb-n4" style="z-index: 1000; position: relative">
                    <img src="{{ profile_user.userprofileinfo.get_profile_pic }}"
                         class="rounded-circle h-100 border border-dark border-5"
                         alt="Avatar" />
                    {% if is_user_profile %}
                        <div type="button"
                             class="h-100 w-100 rounded-circle profile-image-info"
                             style="position: absolute;
                                    top: 0"
                             data-bs-toggle="modal"
                             data-bs-target="#profileImageModal">
                            <div class="fs-3 d-flex h-100">
                                <i class="bi bi-camera-fill m-auto"></i>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            {% if is_user_profile %}
                <div type="button"
                     data-bs-toggle="modal"
                     data-bs-target="#profileBannerModal"
                     class="card-img-overlay d-flex flex-column justify-content-end align-items-center p-0 profile-banner-info">
                    <div class="ms-auto mt-auto mb-2 me-2 fs-3">
                        <i class="bi bi-camera-fill mt-auto ms-auto"></i>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="card-body">
            <div class="row" id="title">
                <div class="col-auto">
                    <div class="fs-6 my-auto">u/{{ profile_user.username }}</div>
                    <div class="fs-2 fw-bold text-white">{{ profile_user.first_name }} {{ profile_user.last_name }}</div>
                </div>
            </div>
            <div class="row" id="information">
                <div class="col d-flex gap-4">
                    <div class="d-flex gap-2 btn btn-link p-0 fs-5"
                         data-bs-toggle="modal"
                         data-bs-target="#profileFollowersModal">
                        <div class="m-auto">
                            <i class="bi bi-people-fill fw-normal"></i>
                        </div>
                        <div class="fw-semibold">{{ profile_followers_list.count }}</div>
                        <div class="user-select-none fw-normal">{% trans "Follower" %}</div>
                    </div>
                    <div class="d-flex gap-2 btn btn-link p-0 fs-5"
                         data-bs-toggle="modal"
                         data-bs-target="#profileFollowingModal">
                        <div class="m-auto">
                            <i class="bi bi-person-heart fw-normal"></i>
                        </div>
                        <div class="fw-semibold">{{ profile_following_list.count }}</div>
                        <div class="user-select-none fw-normal">{% trans "Gefolgt" %}</div>
                    </div>
                </div>
            </div>
            {% if is_user_profile %}
                <div class="row mt-2" id="bio">
                    <div class="col fs-5">
                        <div class="d-flex gap-2">
                            <div class="d-flex btn btn-link p-0 fs-5"
                                 data-bs-toggle="modal"
                                 data-bs-target="#profileBiographyModal">
                                <div class="mb-auto pt-1">
                                    <i class="bi bi-blockquote-right"></i>
                                </div>
                            </div>
                            <div>
                                {% if profile_user.biography %}
                                    {{ profile_user.biography|linebreaks }}
                                {% else %}
                                    <i>{% trans "Keine Biografie gesetzt." %}</i>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mt-2" id="newPost">
                    <div class="col-auto ms-auto">
                        <button class="btn btn-outline-primary ms-auto"
                                type="button"
                                data-bs-toggle="modal"
                                data-bs-target="#postCreateModal">{% trans "Neuer Post" %}</button>
                    </div>
                </div>
            {% else %}
                {% if profile_user.biography %}
                    <div class="row mt-2" id="bio">
                        <div class="col fs-5">
                            <div class="d-flex gap-2">
                                <div class="mb-auto pt-1">
                                    <i class="bi bi-blockquote-right"></i>
                                </div>
                                <div>{{ profile_user.biography }}</div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="row mt-2" id="buttons">
                    <div class="col-auto">
                        <a class="btn btn-outline-primary"
                           href="{% url 'messaging_app:inbox_chat' profile_user.username %}">
                            <div class="d-flex gap-2">
                                <div class="m-auto">
                                    <i class="bi bi-chat-dots-fill"></i>
                                </div>
                                <div>{% trans "Nachricht senden" %}</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-auto">
                        <a class="btn btn-outline-primary"
                           href="{% url 'dashboard_app:watchlist' profile_user.username 'no_sort' 'n' %}">
                            <div class="d-flex gap-2">
                                <div class="m-auto">
                                    <i class="bi bi-star-fill"></i>
                                </div>
                                <div>{% trans "Watchlist ansehen" %}</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-auto">
                        <a class="btn btn-outline-primary"
                           href="{% url 'user_app:follow' profile_user.username %}">
                            <div class="d-flex gap-2">
                                {% if is_user_following %}
                                    <div class="m-auto">
                                        <i class="bi bi-person-dash-fill"></i>
                                    </div>
                                    <div>{% trans "Entfolgen" %}</div>
                                {% else %}
                                    <div class="m-auto">
                                        <i class="bi bi-person-plus-fill"></i>
                                    </div>
                                    <div>{% trans "Folgen" %}</div>
                                {% endif %}
                            </div>
                        </a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    {% if not is_user_profile and not portfolio_privacy_setting == "private" and has_transactions %}
        <div>
            {# Portfolio Chart #}
            <div class="row mt-4">
                <div class="col">
                    <div class="card">
                        <div class="card-header fs-3 fw-semibold text-white">{% trans "Kursverlauf" %}</div>
                        <div class="card-body">
                            <div id="range_selection"
                                 class="btn-group w-100 overflow-auto"
                                 role="group">
                                <a href="{% url "user_app:profile" profile_user.username 0 %}"
                                   class="btn btn-secondary border text-body">
                                    <div class="fw-semibold">{% trans "Gesamt" %}</div>
                                    <div class="fs-4 {% if line_data.button_values.all >= 0 %} text-success-emphasis {% else %} text-danger-emphasis {% endif %}"
                                         id="whole">{{ line_data.button_values.all|to_percentage }}</div>
                                </a>
                                <a href="{% url "user_app:profile" profile_user.username 0 %}"
                                   class="btn btn-secondary border text-body">
                                    <div class="fw-semibold">{% trans "Jahr" %}</div>
                                    <div class="fs-4 {% if line_data.button_values.1year >= 0 %} text-success-emphasis {% else %} text-danger-emphasis {% endif %}"
                                         id="year">{{ line_data.button_values.1year|to_percentage }}</div>
                                </a>
                                <a href="{% url "user_app:profile" profile_user.username 0 %}"
                                   class="btn btn-secondary border text-body">
                                    <div class="fw-semibold">{% trans "6 Monate" %}</div>
                                    <div class="fs-4 {% if line_data.button_values.6month >= 0 %} text-success-emphasis {% else %} text-danger-emphasis {% endif %}"
                                         id="sixmonths">{{ line_data.button_values.6month|to_percentage }}</div>
                                </a>
                                <a href="{% url "user_app:profile" profile_user.username 0 %}"
                                   class="btn btn-secondary border text-body">
                                    <div class="fw-semibold">{% trans "Monat" %}</div>
                                    <div class="fs-4 {% if line_data.button_values.1month >= 0 %} text-success-emphasis {% else %} text-danger-emphasis {% endif %}"
                                         id="month">{{ line_data.button_values.1month|to_percentage }}</div>
                                </a>
                                <a href="{% url "user_app:profile" profile_user.username 0 %}"
                                   class="btn btn-secondary border text-body">
                                    <div class="fw-semibold">{% trans "Woche" %}</div>
                                    <div class="fs-4 {% if line_data.button_values.1week >= 0 %} text-success-emphasis {% else %} text-danger-emphasis {% endif %}"
                                         id="week">{{ line_data.button_values.1week|to_percentage }}</div>
                                </a>
                            </div>
                            <div class="row mt-4">
                                <div class="col-md-9">
                                    {# Line Chart #}
                                    <div style="height:40vh">
                                        <canvas id="lineChart" style="height:100%"></canvas>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    {# Pie Chart #}
                                    <div class="d-flex flex-column justify-content-center align-items-center"
                                         style="height:40vh">
                                        <canvas id="pieChart" style="z-index: 100;"></canvas>
                                        <div class="position-absolute">
                                            <div class="text-center fw-semibold" id="pieTitle">{% trans "Gesamtwert" %}</div>
                                            <div class="text-center fs-3" id="pieValue">{{ kpi_total|to_locale_valuta }}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    {# Create post #}
    <div class="row mt">
        <div class="col d-flex flex-column gap-3">
            {% for post in myposts %}
                {% if not post.privacy_settings == 'private' or post.user_id == request.user.id %}
                    {% entry request.user post %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
    {# Charts JS-Script #}
    {% include_chart %}
    {% line_chart line_data %}
    {% pie_chart pie_data %}
    {# Modals #}
    {% if is_user_profile %}
        {% profile_image_modal request.user %}
        {% profile_banner_modal request.user %}
        {% profile_biography_modal request.user %}
        {% post_create_modal request.user %}
    {% endif %}
    {% profile_followers_modal request profile_user profile_followers_list user_following_list %}
    {% profile_following_modal request profile_user profile_following_list user_following_list %}
{% endblock content %}