app/app/urls.py
from django.contrib import admin
from django.urls import path, include

from app import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('user_app.urls')),
    path('', include('core.urls')),
    path('api/', include('api_app.urls')),
    path('dashboard/', include('dashboard_app.urls')),
    path('settings/', include('settings_app.urls')),
    path('community/', include('community_app.urls')),
    path('messaging/', include('messaging_app.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/community_app/urls.py
""" Routes for the community_app """

from django.urls import path
from community_app.views import main, post, comment

app_name = 'community_app'

urlpatterns = [
    # Main
    path('community/<str:feed>/', main.community, name="community"),

    # Comment
    path('comment/add/<int:post_id>', comment.create, name="comment_create"),
    path('comment/like/<int:comment_id>', comment.like_comment, name="like_comment"),
    path('comment/delete/<int:comment_id>',
         comment.delete, name="comment_delete"),

    # Post
    path('post/like/<int:post_id>', post.like_toggle, name="like_toggle"),
    path('post/create', post.create, name="post_create"),
    path('post/delete/<int:post_id>', post.delete, name="post_delete"),
]

app/user_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PasswordCustomResetForm, PasswordCustomSetForm
from .views import profile, auth, profile_edit

app_name = 'user_app'

urlpatterns = [
    # Loading and redirecting to profile page 
    path('profile-redirect/', profile.profile_redirect, name='profile_redirect'),
    path('profile/<str:username>/<int:timespan>/',
         profile.profile, name='profile'),

    # Following 
    path('follow/<str:username>', profile.toggle_follow, name='follow'),

    # Update Routes       
    path('update/userprofile/<int:pk>',
          profile_edit.ProfilePicUpdateView.as_view(), name='update_userprofile'),   
    path('update/userbanner/<int:pk>',
          profile_edit.ProfileBannerUpdateView.as_view(), name='update_userbanner'),
    path("update/biography", 
         profile_edit.BiographyUpdateView.as_view(), name="update_biography"),
    path('delete/userprofile/<int:pk>',
         profile_edit.delete_profile_pic, name='delete_userprofile'),

    # Registration
    path('register', auth.register, name='register'),
    path('register/success', auth.register_success, name='register_success'),

    # Auth
    path('login', auth_views.LoginView.as_view(
        template_name='user_app/login.html', authentication_form=UserLoginForm), name='login'),
    path('logout', auth_views.LogoutView.as_view(
        template_name='core/landing.html'), name='logout'),

    # Password reset
    path('password-reset/',
         auth.ResetPasswordView.as_view(
             template_name="user_app/password_recovery/reset_password.html",
             form_class=PasswordCustomResetForm),
         name='reset_password'),
    path('password-reset-sent/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="user_app/password_recovery/reset_password_sent.html"),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth.ConfirmResetPasswordView.as_view(
             template_name="user_app/password_recovery/reset_password_confirm.html",
             form_class=PasswordCustomSetForm),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="user_app/password_recovery/reset_password_complete.html"),
         name='password_reset_complete'),
]

app/community_app/models.py
from django.db import models
from user_app.models import CustomUser
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    content = models.CharField(max_length=1000)
    created_at = models.DateTimeField()
    tags = models.CharField(max_length=100)
    image = models.ImageField(upload_to='post_images/', blank=True)
    privacy_settings = models.CharField(max_length=10, default="all")

    def __str__(self):
        return self.content


class PostLike(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.user


class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=1000)
    created_at = models.DateTimeField()
    image = models.ImageField(upload_to='comment_images/', blank=True)

    def __str__(self):
        return self.user
    
class CommentLike(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

    def __str__(self):
        return self.user_id
    
class Tag(models.Model):
    tagname = models.CharField(max_length=20)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

app/community_app/forms.py
from django import forms


class PostForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(attrs={
        "id": "content",
        "class": "form-control",
        "placeholder": "Text eingeben ...",
        "rows": "5"
    }), max_length=1000)
    tags = forms.CharField(widget=forms.TextInput(attrs={
        "id": "tags",
        "class": "form-control"
    }), max_length=100, required=False)
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'id': "image_To_Upload",
        "class": "form-control"
    }), required=False)

app/community_app/views/comment.py
""" view-functions related to community_app.comment """

from datetime import datetime
import json
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from notification_app.methods import get_notifications, send_notification
from notification_app.consumer import NotificationConsumer
from community_app.models import Comment, Post, CommentLike
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from django.core import serializers


channel_layer = get_channel_layer()


def create(request, post_id):
    """
    Create a 'Comment' related to a given post.

    Keyword arguments:
        post_id: The id of the post to be commented.
    """
    post = Post.objects.filter(id=post_id).get()

    Comment.objects.create(
        user=request.user,
        post=post,
        content=request.POST.get("post_comment"),
        created_at=datetime.now()
    )

    send_notification(channel_layer, post.user.id, "comment",
                      f"{request.user.username} commented on your post.")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def delete(request, comment_id):
    """
    Delete a 'Comment' by its id.

    Keyword arguments:
        id: The id of the 'Comment' to be deleted.
    """

    Comment.objects.filter(id=comment_id).delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def like_comment(request, comment_id):
    """
    Toggles a 'CommentLikes' entrie by a given comment_id and the requesting user.

    Keyword arguments:
        comment_id: The id of the 'Comment' to be liked.
    """

    # Try deleting database entry
    try:
        CommentLike.objects.filter(
            user=request.user.id, comment=comment_id).get().delete()

    # Else create new entry
    except ObjectDoesNotExist:
        CommentLike.objects.create(user=request.user,
                                   comment=Comment.objects.get(id=comment_id))

    comment = Comment.objects.filter(id=comment_id).get()
    send_notification(channel_layer, comment.post.user.id, "like",
                      f"{request.user.username} liked your comment.")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

app/community_app/views/post.py
""" view-functions related to community_app.post """

from datetime import datetime

from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from community_app.models import Post, PostLike, Tag
from community_app.forms import PostForm
from notification_app.methods import send_notification
from messaging_app.utils import compress_image
from settings_app.models import Settings
from channels.layers import get_channel_layer


channel_layer = get_channel_layer()


def create(request):
    """ Create a new 'Post' from PostForm(). """
    settings = Settings.objects.get(user=request.user)
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        form_data = form.cleaned_data

        post = Post.objects.create(
            user_id=request.user.id,
            content=form_data.get("content"),
            created_at=datetime.now(),
            image=form_data.get("image"),
            tags=form_data.get("tags"),
            privacy_settings=settings.posts_privacy_settings
        )
        j = form_data.get("tags").split(",")
        for t in j:
            Tag.objects.get_or_create(tagname=t, post=post)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def delete(request, post_id):
    """
    Delete a 'Post' by its id.

    Keyword arguments:
        id: The id of the 'Post' to be deleted.
    """

    Post.objects.filter(id=post_id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def get_by_feed(feed, **kwargs):
    """
    Get a filtered set of 'Posts'.

    Keyword arguments:
        feed: The feed to be filtered by.
        ** kwargs: The filter values.
    """

    posts = Post.objects.select_related("user", "user__userprofileinfo")
    posts = posts.order_by("-created_at")

    match feed:
        case "follower":
            posts = posts.filter(
                user_id__followers__follower_user_id=kwargs.get("user_id"))

        case "personal":
            posts.filter(user_id=kwargs.get("user_id"))

    return posts


def get_by_tag(tag, **kwargs):
    tags = Tag.objects.filter(tagname=tag)
    posts = []
    for tag in tags:
        post = Post.objects.get(id=tag.post_id)
        posts.append(post)

    return posts


def get_by_user(user, **kwargs):
    posts = Post.objects.filter(user_id=user.id)
    return posts.order_by("-created_at")


def like_toggle(request, post_id):
    """
    Toggles a 'PostLikes' entrie by a given post_id and the requesting user.

    Keyword arguments:
        post_id: The id of the 'Post' to be toggled.
    """

    # Try deleting database entry
    try:
        PostLike.objects.filter(
            user=request.user.id, post=post_id).get().delete()

    # Else create new entry
    except ObjectDoesNotExist:
        PostLike.objects.create(user=request.user,
                                post=Post.objects.get(id=post_id))

    post = Post.objects.filter(id=post_id).get()

    send_notification(channel_layer, post.user.id, "like",
                      f"{request.user.username} liked your post.")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

app/community_app/templates/community_app/inclusion/post.html
{% load i18n %}
{% load community_tags %}
<div class="card" id="post_{{ post.id }}">
    <div class="card-header d-flex">
        {# User information #}
        <div id="user_information" class="text-start p-0 d-flex gap-2 ">
            <div class="my-auto">
                <img class="logo-fs-3"
                    src="{{ post.user.userprofileinfo.get_profile_pic }}">
            </div>
            <div>
                <a class="btn btn-link text-start p-0 text-body"
                   href="{% url 'user_app:profile' post.user.username 0 %}">
                    <div class="fw-semibold text-white fs-5">{{ post.user.first_name }} {{ post.user.last_name }}</div>
                </a>
                <div>
                    <small>{{ post.created_at|datetime_converter }}</small>
                </div>
            </div>
        </div>
        {# Post settings #}
        {% if user.id == post.user.id %}
            <div class="dropdown ms-auto my-auto">
                <button class=" btn btn-outline-primary p-2 fs-5"
                        data-bs-toggle="dropdown"
                        aria-expanded="false">
                    <i class="bi bi-three-dots"></i>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <a class="dropdown-item" href="#"><i class="bi bi-gear-fill pe-2"></i>{% trans "Bearbeiten" %}</a>
                    </li>
                    <li>
                        <a class="dropdown-item text-danger-emphasis" href="{% url 'community_app:post_delete' post.id %}"><i class="bi bi-trash-fill pe-2"></i>{% trans "Löschen" %}</a>
                    </li>
                </ul>
            </div>
        {% endif %}
    </div>
    {# Post Content #}
    <div class="card-body pb-2">
        <div id="content">{{ post.content|tag|linebreaksbr }}</div>
        {# Post Image #}
        {% if post.image != "" %}
            <button class="btn btn-outline-primary ms-auto"
                type="button"
                data-bs-toggle="modal"
                data-bs-target="#fullImageModal{{post.id}}">
                <img src="{{ post.image.url }}" style="width:200px;"/>
            </button>
            {% full_image_modal post %}
        {% endif %}
        <div class="border-top mt-3 mb-2"></div>
        {# Post information #}
        <div id="post_information" class="d-flex">
            {# Tags #}
            <div>
                {% for tag in post.tags|to_tag_list %}
                    {% if tag %}
                    <a href="{% url 'community_app:community' tag %}" class="btn btn-link p-0 " onclick="">
                        <small>#{{ tag }}</small>
                    </a>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="d-flex ms-auto gap-4">
                {# Likes #}
                <a href="{% url 'community_app:like_toggle' post.id %}"
                   class="btn btn-link p-0 fw-bold">
                    <small class="d-flex gap-1">
                        <div class="my-auto">
                            <i class="bi bi-heart-fill m-auto"></i>
                        </div>
                        <div class="my-auto">{{ post.postlike_set.count }}</div>
                        <div class="my-auto">{% trans "Likes" %}</div>
                    </small>
                </a>
                {# Comments #}
                <a href="#post_{{ post.id }}_comments"
                   class="btn btn-link p-0 fw-bold"
                   data-bs-toggle="collapse"
                   role="button"
                   aria-expanded="true"
                   aria-controls="#post_{{ post.id }}_comments">
                    <small class="d-flex gap-1">
                        <div class="my-auto">
                            <i class="bi bi-card-text"></i>
                        </div>
                        <div class="my-auto">{{ post.comment_set.count }}</div>
                        <div class="my-auto">{% trans "Kommentare" %}</div>
                    </small>
                </a>
            </div>
        </div>
    </div>
    <div class="card-footer">
        {# Comment section #}
        <div class="collapse", id="post_{{ post.id }}_comments">
            {% for comment in post.comment_set.all %}
                <div class="d-flex gap-2 mb-3">
                    <div>
                        <img class="logo-fs-3 mt-1"
                            src="{{ comment.user.userprofileinfo.get_profile_pic }}">
                    </div>
                    <div>
                        {# Header #}
                        <div class="d-flex gap-2">
                            <a class="btn btn-link text-start p-0 text-body"
                               href="{% url 'user_app:profile' comment.user.username 0 %}">
                                <div>
                                    <small>u/{{ comment.user.username }}</small>
                                </div>
                                <div class="fw-semibold text-white">{{ comment.user_id.first_name }} {{ comment.user_id.last_name }}</div>
                            </a>
                            <div class="d-flex mt-auto gap-2">
                                <div class="mt-auto">
                                    <small>{{ comment.created_at|datetime_converter }}</small>
                                </div>
                                {% if comment.user.id == user.id %}
                                    <a class="btn btn-link btn-link-danger p-0"
                                       href="{% url 'community_app:comment_delete' comment.id %}">
                                        <small class="d-flex text-center">
                                            <i class="bi bi-trash-fill pe-1 m-auto"></i>
                                            <div>{% trans "Löschen" %}</div>
                                        </small>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                        {# Comment Content #}
                        <div>{{ comment.content|tag|linebreaksbr }}</div>
                        {# Likes #}
                        <a href="{% url 'community_app:like_comment' comment.id %}"
                        class="btn btn-link p-0 fw-bold">
                            <small class="d-flex gap-1">
                                <div class="my-auto">
                                    <i class="bi bi-heart-fill m-auto"></i>
                                </div>
                                <div class="my-auto">{{ comment.commentlike_set.count }}</div>
                                <div class="my-auto">{% trans "Likes" %}</div>
                            </small>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
        {# Add comment #}
        <div>
            {% trans "Schreibe einen Kommentar..." as comment_annotation %}
            <form class="my-2 d-flex gap-2"
                  method="post"
                  action="{% url 'community_app:comment_create' post.id %}">
                {% csrf_token %}
                <textarea class="form-control"
                          name="post_comment"
                          rows="1"
                          placeholder="{{comment_annotation}}"></textarea>
                <button class="btn btn-outline-primary d-flex gap-2 m-auto" type="submit">
                    <div>{% trans "Kommentieren" %}</div>
                </button>
            </form>
        </div>
    </div>
</div>